<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Film;

class FilmsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        Film::insert([
            [
                'id' => 1,
                'film_name' => 'Linh Miêu',
                'thumbnail' => 'https://phimimg.com/upload/vod/20241216-1/87b3bf4f9465892275ade60894320551.jpg',
                'duration' => 109,
                'review' => 4.50,
                'story_line' => 'Linh Miêu: Quỷ Nhập Tràng lấy cảm hứng từ truyền thuyết dân gian về “quỷ nhập tràng” để xây dựng cốt truyện. Phim lồng ghép những nét văn hóa đặc trưng của Huế như nghệ thuật khảm sành - một văn hóa đặc sắc của thời nhà Nguyễn, đề cập đến các vấn đề về giai cấp và quan điểm trọng nam khinh nữ. Đặc biệt, hình ảnh rước kiệu thây ma và những hình nhân giấy không chỉ biểu trưng cho tai ương hay điềm dữ mà còn là hiện thân của nghiệp quả.',
                'link_trailer' => 'https://www.youtube.com/watch?v=QBMhv3FLW_Q&t=1s',
                'movie_genre' => 'Horror',
                'censorship' => '18+',
                'language' => 'Vietnamese',
                'director' => 'Luu Thanh Luan',
                'actor' => 'Hong Dao, Samuel An, Nguyen Thuc Thuy Tien, Thien An, Van Anh',
                'status' => 0,
                'release' => '2024-12-22',
                'created_at' => '2024-12-20 09:32:51',
                'updated_at' => '2024-12-21 16:59:33',
            ],
            [
                'id' => 2,
                'film_name' => 'Kraven: The Hunter',
                'thumbnail' => 'https://res.cloudinary.com/dcjbbvqxe/image/upload/v1734800319/films/thumbnails/dzydzzuycnta5az50qgu.jpg',
                'duration' => 127,
                'review' => 4.80,
                'story_line' => 'Kraven\'s complex relationship with his ruthless father, Nikolai Kravinoff, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.',
                'link_trailer' => 'https://www.youtube.com/watch?v=I8gFw4-2RBM',
                'movie_genre' => 'Action, Thriller',
                'censorship' => '18+',
                'language' => 'English',
                'director' => 'J.C. Chandor',
                'actor' => 'Aaron Taylor-Johnson, Ariana DeBose, Fred Hechinger',
                'status' => 0,
                'release' => '2024-12-13',
                'created_at' => '2024-12-20 09:32:51',
                'updated_at' => '2024-12-21 17:00:22',
            ],
            [
                'id' => 3,
                'film_name' => 'Devils Stay',
                'thumbnail' => 'https://res.cloudinary.com/dcjbbvqxe/image/upload/v1734799925/films/thumbnails/uasrhenvpepwlpkbv310.jpg',
                'duration' => 95,
                'review' => 4.80,
                'story_line' => 'A heart specialist doubts his daughter\'s death after an exorcism, believing her heart still beats. Amid her three-day funeral, he and a priest clash over the truth, each trying to prove their stance and potentially save her life.',
                'link_trailer' => 'https://www.youtube.com/watch?v=sqkTqjd_Ls4',
                'movie_genre' => 'Horror',
                'censorship' => '18+',
                'language' => 'Korean',
                'director' => 'Moon-Sub Hyun',
                'actor' => 'Park Shin-yang, Lee Min-ki, Lee Re',
                'status' => 0,
                'release' => '2024-12-13',
                'created_at' => '2024-12-20 09:32:51',
                'updated_at' => '2024-12-21 16:52:06',
            ],
            [
                'id' => 4,
                'film_name' => 'Moana 2',
                'thumbnail' => 'https://res.cloudinary.com/dcjbbvqxe/image/upload/v1734800169/films/thumbnails/kweejb1lmagiswd0vatt.jpg',
                'duration' => 100,
                'review' => 4.58,
                'story_line' => 'After receiving an unexpected call from her wayfinding ancestors, Moana must journey to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she\'s ever faced.',
                'link_trailer' => 'https://www.youtube.com/watch?v=hDZ7y8RP5HE&t=6s',
                'movie_genre' => 'Animation, Adventure, Comedy, Family, Fantasy, Musical',
                'censorship' => '15+',
                'language' => 'English',
                'director' => 'David G. Derrick Jr., Jason Hand, Dana Ledoux Miller',
                'actor' => 'Auli\'i Cravalho, Dwayne Johnson, Hualalai Chung',
                'status' => 0,
                'release' => '2024-12-04',
                'created_at' => '2024-12-20 09:32:51',
                'updated_at' => '2024-12-21 17:01:06',
            ],
            [
                'id' => 5,
                'film_name' => 'Disaster Holiday',
                'thumbnail' => 'https://phimimg.com/upload/vod/20241216-1/1784b879fbe179018bb15b58ab0bd28e.jpg',
                'duration' => 93,
                'review' => 4.50,
                'story_line' => 'Dad promises an exotic vacation but mistakenly books Durban instead of Zanzibar. Chaos ensues as the family\'s dream trip spirals into hilarity, while dad scrambles to secure a promotion.',
                'link_trailer' => 'https://www.youtube.com/watch?v=6LzcJW6XBlQ',
                'movie_genre' => 'Comedy, Family',
                'censorship' => '15+',
                'language' => 'English',
                'director' => 'Rethabile Ramaphakela',
                'actor' => 'Rethabile Ramaphakela, Lunathi Mampofu, Kopano Mahlasi, Lubabalo Tala, Yeya Ralarala',
                'status' => 0,
                'release' => '2024-12-16',
                'created_at' => '2024-12-20 09:32:51',
                'updated_at' => '2024-12-21 16:06:14',
            ],
            [
                'id' => 6,
                'film_name' => 'Mufasa: The Lion King',
                'thumbnail' => 'https://media.lottecinemavn.com/Media/MovieFile/MovieImg/202412/11464_103_100003.jpg',
                'duration' => 118,
                'review' => 4.50,
                'story_line' => 'Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.',
                'link_trailer' => 'https://www.youtube.com/watch?v=lMXh6vjiZrI',
                'movie_genre' => 'Animation, Adventure, Drama, Family, Fantasy, Musical',
                'censorship' => '15+',
                'language' => 'English',
                'director' => 'Barry Jenkins',
                'actor' => 'Kelvin Harrison Jr., Aaron Pierre, Tiffany Boone, Mads Mikkelsen',
                'status' => 1,
                'release' => '2024-12-18',
                'created_at' => '2024-12-20 09:32:51',
                'updated_at' => '2024-12-21 16:06:57',
            ],
            [
                'id' => 7,
                'film_name' => 'Sonic the Hedgehog 3',
                'thumbnail' => 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/s/t/sth3_poster_470x700.jpg',
                'duration' => 109,
                'review' => 4.50,
                'story_line' => 'Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.',
                'link_trailer' => 'https://www.youtube.com/watch?v=qSu6i2iFMO0',
                'movie_genre' => 'Action, Adventure, Comedy, Family, Fantasy, Sci-Fi',
                'censorship' => '13+',
                'language' => 'English',
                'director' => 'Jeff Fowler',
                'actor' => 'Ben Schwartz, Colleen Shaughnessey, Idris Elba',
                'status' => 1,
                'release' => '2024-12-27',
                'created_at' => '2024-12-20 09:32:51',
                'updated_at' => '2024-12-21 16:07:45',
            ],
            [
                'id' => 8,
                'film_name' => 'Kính Vạn Hoa: Bắt Đền Con Ma',
                'thumbnail' => 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/3/5/350x490.jpg',
                'duration' => 110,
                'review' => 4.50,
                'story_line' => 'Sau sự thành công của hai phim điện ảnh chuyển thể từ hai tác phẩm đình đám của nhà văn Nguyễn Nhật Ánh, một tác phẩm nổi bật khác của nhà văn hiện đại thành công nhất Việt Nam chuẩn bị được đưa lên màn ảnh rộng: “Kính Vạn Hoa”. Và đạo diễn dự án bom tấn này là “đạo diễn trăm tỷ” Võ Thanh Hòa.',
                'link_trailer' => 'https://www.youtube.com/watch?v=DsTUfZ0h_KM&t=2s',
                'movie_genre' => 'Hài hước, Phiêu lưu',
                'censorship' => '13+',
                'language' => 'Vietnamese',
                'director' => 'Võ Thanh Hòa',
                'actor' => 'Hung Anh, Nhat Linh, Phuong Duyen, Ngoc Trai',
                'status' => 1,
                'release' => '2024-12-24',
                'created_at' => '2024-12-20 09:32:51',
                'updated_at' => '2024-12-21 16:53:20',
            ],
            [
                'id' => 9,
                'film_name' => 'Hear Me: Our Summer',
                'thumbnail' => 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/4/7/470x700px.jpg',
                'duration' => 120,
                'review' => 4.70,
                'story_line' => 'A hearing-impaired woman and a motorbike delivery man find connection despite communication barriers. They use metaphors of persevering water birds and trees to represent overcoming obstacles in romance and leading to further commitment.',
                'link_trailer' => 'https://www.youtube.com/watch?v=9rSz2Ve2XH8',
                'movie_genre' => 'Romance',
                'censorship' => '13+',
                'language' => 'Korean',
                'director' => 'Cho Sun-Ho',
                'actor' => 'Hong Kyung, Roh Yoon Seo, Kim Min Ju',
                'status' => 1,
                'release' => '2024-12-20',
                'created_at' => '2024-12-20 09:32:51',
                'updated_at' => '2024-12-21 16:10:37',
            ],
            [
                'id' => 10,
                'film_name' => '404 Run Run',
                'thumbnail' => 'https://res.cloudinary.com/dcjbbvqxe/image/upload/v1734797572/films/thumbnails/tjdn3fxtvavd5crcd8ja.jpg',
                'duration' => 120,
                'review' => 4.70,
                'story_line' => 'A swindler\'s luxury hotel scheme turns spectacularly supernatural in a spooky battle of wits and wraiths. A comedic ghost story unfolds as \'Nakrob\', a young real estate swindler, discovers an abandoned hillside hotel by the beach. Seeing an opportunity, he decides to turn it into a luxury hotel scam. However, Nakrob soon realizes that the hotel is still occupied by the ghost of its original owner, \'Lalita\', who continues to haunt every inch of the property. Lalita\'s ghost inflicts inexplicable horrors on anyone attempting to claim ownership after hers. Thus, a battle ensues between the living and the dead. Nakrob, gathering shamans from various faith communities, attempts to expel Lalita, while she uses all her spectral power to haunt the intruders until their demise.',
                'link_trailer' => 'https://www.youtube.com/watch?v=bTJ-fHJopAI',
                'movie_genre' => 'Comedy, Horror',
                'censorship' => '18+',
                'language' => 'Thai',
                'director' => 'Pichaya Jarusboonpracha',
                'actor' => 'Chantavit Dhanasevi, Kanyawee Songmuang, Pittaya Saechua',
                'status' => 1,
                'release' => '2024-12-27',
                'created_at' => '2024-12-20 09:32:51',
                'updated_at' => '2024-12-21 16:12:52',
            ],
            [
                'id' => 11,
                'film_name' => 'Nosferatu',
                'thumbnail' => 'https://res.cloudinary.com/dcjbbvqxe/image/upload/v1734797980/films/thumbnails/ubqkt00ei0ahr1fv4n8d.jpg',
                'duration' => 133,
                'review' => 4.30,
                'story_line' => 'A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.',
                'link_trailer' => 'https://www.youtube.com/watch?v=nulvWqYUM8k',
                'movie_genre' => 'Fantasy, Horror, Mystery',
                'censorship' => '18+',
                'language' => 'English',
                'director' => 'Robert Eggers',
                'actor' => 'Lily-Rose, DeppNicholas, HoultBill Skarsgård',
                'status' => 1,
                'release' => '2024-12-25',
                'created_at' => '2024-12-21 16:19:41',
                'updated_at' => '2024-12-21 16:23:11',
            ],
            [
                'id' => 12,
                'film_name' => 'Alien Wars: Judgement Day',
                'thumbnail' => 'https://res.cloudinary.com/dcjbbvqxe/image/upload/v1734798653/films/thumbnails/tbauw38rb0ywoyb4tsk0.jpg',
                'duration' => 90,
                'review' => 4.20,
                'story_line' => 'After an alien catastrophe, a few remaining human souls try to hold on to their sanity and their reality as humanity slowly slips into darkness.',
                'link_trailer' => 'https://www.youtube.com/watch?v=eJ4DZnQMxBs',
                'movie_genre' => 'Sci-Fi',
                'censorship' => '18+',
                'language' => 'English',
                'director' => 'Jeffrey Schneider',
                'actor' => 'Donna Hamblin, Nick Dent, Frederick Ortmann',
                'status' => 1,
                'release' => '2024-12-29',
                'created_at' => '2024-12-21 16:30:54',
                'updated_at' => '2024-12-21 16:32:10',
            ],
            [
                'id' => 13,
                'film_name' => 'Apophis 2029',
                'thumbnail' => 'https://res.cloudinary.com/dcjbbvqxe/image/upload/v1734798977/films/thumbnails/izpf0jxkkaeqs9vijo3m.jpg',
                'duration' => 96,
                'review' => 4.50,
                'story_line' => 'On April 13, 2029, asteroid Apophis grazes Earth, passing below satellites and briefly disappearing from view before re-emerging.',
                'link_trailer' => 'https://www.youtube.com/watch?v=8zMABd7zBL0',
                'movie_genre' => 'Drama',
                'censorship' => '15+',
                'language' => 'English',
                'director' => 'Jeffrey Schneider',
                'actor' => 'Jeffrey Schneider, Nicolette Pullen, Nick Dent',
                'status' => 1,
                'release' => '2024-12-30',
                'created_at' => '2024-12-21 16:36:18',
                'updated_at' => '2024-12-21 16:36:18',
            ],
            [
                'id' => 14,
                'film_name' => 'Quỷ Môn Quan: Phong Ấn',
                'thumbnail' => 'https://res.cloudinary.com/dcjbbvqxe/image/upload/v1734799258/films/thumbnails/iszz3y0hghdpoohigwcb.jpg',
                'duration' => 100,
                'review' => 4.70,
                'story_line' => 'Associated with many terrifying rumors, mysterious suicides and deaths, the Butterfly Building has become the most haunted place in Taipei City. Despite its complexity, this place still attracts many workers to live because of its cheap rent, including Tran Vi - a miserable woman who is looking for a hiding place for herself and her daughter from her violent husband. The story of the sealed door of room 613, the strange behavior of her daughter Nha Nha when she constantly talks to the walls, and the warning "leave as soon as possible" from the building manager and the temple caretaker make Tran Vi increasingly afraid. The terrifying events that follow lead to a series of scary secrets gradually being revealed. Will she be able to protect her daughter and defeat the angry, resentful spirits?',
                'link_trailer' => 'https://www.youtube.com/watch?v=J5t6ypmbMKg&t=30s',
                'movie_genre' => 'Horror',
                'censorship' => '18+',
                'language' => 'Hong Kong',
                'director' => 'Joe Chien',
                'actor' => 'Ivy Yin, Tào Hữu Ninh, Bai Ling, Bai Run Yin, Kaiser Chuang',
                'status' => 1,
                'release' => '2025-01-01',
                'created_at' => '2024-12-21 16:40:58',
                'updated_at' => '2024-12-21 16:40:58',
            ],
            [
                'id' => 15,
                'film_name' => 'Den of Thieves 2: Pantera',
                'thumbnail' => 'https://res.cloudinary.com/dcjbbvqxe/image/upload/v1734799459/films/thumbnails/daey7srnub8nag3ghq0t.jpg',
                'duration' => 144,
                'review' => 4.50,
                'story_line' => 'Butler returns as Big Nick (Butler), this time on the hunt in Europe for Donnie (Jackson Jr.) who is embroiled in the dangerous world of diamond thieves and the infamous Panther mafia as they plot a massive heist of the world\'s biggest diamond exchange.',
                'link_trailer' => 'https://www.youtube.com/watch?v=VY6h1qL2DPY',
                'movie_genre' => 'Action, Crime, Drama, Thriller',
                'censorship' => '15+',
                'language' => 'English',
                'director' => 'Christian Gudegast',
                'actor' => 'Gerard Butler, Jordan Bridges, O\'Shea Jackson Jr.',
                'status' => 1,
                'release' => '2025-01-10',
                'created_at' => '2024-12-21 16:44:20',
                'updated_at' => '2024-12-21 16:44:20',
            ],
            [
                'id' => 17,
                'film_name' => 'Chị Dâu',
                'thumbnail' => 'https://res.cloudinary.com/dcjbbvqxe/image/upload/v1734799657/films/thumbnails/ltupkc1hcflgrok0cjaz.png',
                'duration' => 100,
                'review' => 4.70,
                'story_line' => 'Chuyện bắt đầu khi bà Nhị - con dâu cả của gia đình quyết định nhân dịp đám giỗ của mẹ chồng, tụ họp cả bốn chị em gái - con ruột trong nhà lại để thông báo chuyện sẽ tự bỏ tiền túi ra sửa sang căn nhà từ đường cũ kỹ trước khi bão về.',
                'link_trailer' => 'https://www.youtube.com/watch?v=D7Omh1AQajg',
                'movie_genre' => 'Drama, Comedy',
                'censorship' => '15+',
                'language' => 'Vietnamese',
                'director' => 'Khương Ngọc',
                'actor' => 'Ngọc Trinh, Việt Hương, Hồng Đào',
                'status' => 0,
                'release' => '2024-12-20',
                'created_at' => '2024-12-21 16:47:38',
                'updated_at' => '2024-12-21 16:47:45',
            ],
            [
                'id' => 18,
                'film_name' => 'The Fire Inside',
                'thumbnail' => 'https://res.cloudinary.com/dcjbbvqxe/image/upload/v1734800898/films/thumbnails/jiqfb7qwrvuhpakjyarj.jpg',
                'duration' => 109,
                'review' => 3.40,
                'story_line' => 'The story of Claressa \'T-Rex\' Shields, a boxer from Flint, Michigan who trained to become the first woman in her country\'s history to win an Olympic gold medal in the sport.',
                'link_trailer' => 'https://www.youtube.com/watch?v=KFyNvUmJzmE',
                'movie_genre' => 'Biography, Drama, Sport',
                'censorship' => '15+',
                'language' => 'English',
                'director' => 'Rachel Morrison',
                'actor' => 'Ryan Destiny, Brian Tyree Henry, Jazmin Headley',
                'status' => 0,
                'release' => '2024-12-25',
                'created_at' => '2024-12-21 17:08:19',
                'updated_at' => '2024-12-21 17:12:36',
            ],
            [
                'id' => 19,
                'film_name' => '2073',
                'thumbnail' => 'https://res.cloudinary.com/dcjbbvqxe/image/upload/v1734801010/films/thumbnails/vkl1yhoevsv4ec5gx5dg.jpg',
                'duration' => 85,
                'review' => 3.80,
                'story_line' => 'It will tackle challenges the world faces and is inspired by Chris Marker\'s iconic 1962 featurette La Jetée, about a time traveler who risks his life to change the course of history and save the future of humanity.',
                'link_trailer' => 'https://www.youtube.com/watch?v=YDE97KrYDuU',
                'movie_genre' => 'Biography, Drama, Sport',
                'censorship' => '15+',
                'language' => 'English',
                'director' => 'Asif Kapadia',
                'actor' => 'Samantha Morton, Naomi Ackie, Hector Hewer',
                'status' => 0,
                'release' => '2024-12-27',
                'created_at' => '2024-12-21 17:10:11',
                'updated_at' => '2024-12-21 17:12:43',
            ],
        ]);
    }
}
