version: '3'

networks:
    laravel:
        driver: bridge

services:
    nginx:
        image: nginx:alpine
        container_name: nginx-firm
        restart: unless-stopped
        tty: true
        ports:
            - "8001:8001"
        volumes:
            - ./:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:latest
        container_name: mysql-firm
        restart: unless-stopped
        tty: true
        ports:
            - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel_docker
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes:
            - ./:/var/www/app
        ports:
            - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin-firm
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mysql
        networks:
            - laravel
